[pytest]
markers =
    balloon: tests for the balloon class
    strategy: tests for the strategy class
    game: tests for the game class
    exploit: tests for the explore-then-exploit strategy
    sql: tests for sql implementation
    summary: tests for converting sql to csv summary and saving to correct folder
    full_game: tests for end-to-end game 
