[pytest]
markers =
    engine: tests for new improved multiplayer-allowing engine
    strategies: tests for strategy base class and more sophisticated strategies
    data_gen: tests for tools used in data generation
